In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from joblib import dump

In [2]:
df = pd.read_csv('../positions.csv')
df

ball_x  ball_y  ball_x_vel  ball_y_vel  player_y
0       500.0  325.00        -0.5       -0.25     275.0
1       499.5  324.75        -0.5       -0.25     275.0
2       499.0  324.50        -0.5       -0.25     275.0
3       498.5  324.25        -0.5       -0.25     275.0
4       498.0  324.00        -0.5       -0.25     275.0
...       ...     ...         ...         ...       ...
91004   502.0  326.00         0.5        0.25     195.0
91005   502.5  326.25         0.5        0.25     195.0
91006   503.0  326.50         0.5        0.25     195.0
91007   503.5  326.75         0.5        0.25     195.0
91008   504.0  327.00         0.5        0.25     195.0

[91009 rows x 5 columns]

### Split into train and test data

In [3]:
features = df[['ball_x', 'ball_y', 'ball_x_vel', 'ball_y_vel']].to_numpy()
targets = df[['player_y']].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(features, targets, test_size=0.9)

print(f'x train:\n{x_train}')
print(f'x test:\n{x_test}')
print(f'y train:\n{y_train}')
print(f'y test:\n{y_test}')

x train:
[[ 9.0000e+01  4.5000e+02  5.0000e-01 -2.5000e-01]
 [ 1.3400e+02  7.8000e+01 -5.0000e-01  2.5000e-01]
 [ 1.9500e+02  2.1750e+02  5.0000e-01 -2.5000e-01]
 ...
 [ 5.7650e+02  1.4325e+02 -5.0000e-01 -2.5000e-01]
 [ 7.6550e+02  5.7750e+01  5.0000e-01  2.5000e-01]
 [ 1.5600e+02  3.2300e+02  5.0000e-01  2.5000e-01]]
x test:
[[ 4.2300e+02  4.7350e+02 -5.0000e-01  2.5000e-01]
 [ 6.1600e+02  5.6300e+02 -5.0000e-01 -2.5000e-01]
 [ 7.5650e+02  4.3325e+02  5.0000e-01  2.5000e-01]
 ...
 [ 7.7500e+01  4.7625e+02 -5.0000e-01  2.5000e-01]
 [ 9.8600e+02  5.5800e+02 -5.0000e-01 -2.5000e-01]
 [ 7.4350e+02  2.4675e+02  5.0000e-01  2.5000e-01]]
y train:
[[403.]
 [ 73.]
 [227.]
 ...
 [117.]
 [ 70.]
 [230.]]
y test:
[[384.]
 [545.]
 [315.]
 ...
 [399.]
 [484.]
 [211.]]


### Fit the model

In [4]:
reg = LinearRegression()
reg.fit(x_train, y_train)
reg.score(x_train, y_train)

0.8869807719080147

Find r2 score and mean squared error

In [5]:
predictions = reg.predict(x_test)

print(f' r2: {r2_score(y_test, predictions)}')
print(f'MSE: {mean_squared_error(y_test, predictions)}')

 r2: 0.8876518601264147
MSE: 3355.387232398045


### Save the model so it can be loaded in the game

In [6]:
dump(reg, 'model.joblib')

['model.joblib']